### ISSUE TITLE
Please update these company names in Org Book TEST

### ISSUE THREAD

**Issue by StephanieForbes** [bcgov/orgbook-bc-client#168]
**Change 1:**
Current OrgBook Name: PAY LESS QUALITY DOORS LTD.
Change to: PAYLESS QUALITY DOORS LTD

**Change 2.**
Current OrgBook Name: LEDINGHAM MCALLISTER HOMES LTD.
Change to: LEDINGHAM MCALLISTER

**Comment by amanji** [comment]
@ianco Will this need to be done on the Registries side? Or is this just updating the credential on OrgBook?

**Comment by ianco** [comment]
Name changes will need to be done on the registries side

**Comment by ianco** [comment]
PS  "PAY LESS ..." is BC0607022

"LEDINGHAM ..." there are 2 companies with this name, I think the current company is BC0798947 (the other company had a name change or is inactive)

@StephanieForbes can you confirm these numbers?

**Comment by afillier** [comment]
@ianco I think you're right, and it looks like BC0798947 is the most current (the others I can see exist with different names historically)
FYI @StephanieForbes

**Comment by afillier** [comment]
Hi @amanji  I don't have any way to update these as far as I know in registries because I did not originally create the companies in question. I think you can close this item off, thanks for your help! 

FYI @StephanieForbes 
These names cannot be changed unless we first make the changes in COLIN - but because I did not originally create these companies originally that is not something I have been able to figure out how we can do. As I understand after speaking w/ Alec and team these should not be an issue.
