### ISSUE TITLE
OrgBook website styling

### ISSUE THREAD

**Issue by CharlesMacpherson** [bcgov/orgbook-bc-client#208]
Dwayne Gordon has requested that we improve the styling of the underlined content (within boxes) on the OrgBook home page. The low hanging g p y, etc. with underline does not look nice. Is this aligned with BC Gov style guide?

**Comment by esune** [comment]
@amanji and/or @wadeking98 might have a ready answer about the syle guide since they worked on the refreshed UI:the font family is defined [here](https://github.com/bcgov/orgbook-bc-client/blob/784c7e95e861642e4e7002ad24e120da623a5fc0/src/App.vue#L34) and it seems consistent with what I would expect.

Additionally, I tried out of curiosity using the same styles defined [here](https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/web-content-development-guides/web-style-guide/writing-guide?keyword=font) to display the same sentence `Data Types in OrgBook BC` and, while in OrgBook the link is displayed in bold, the font styling with underlined content displays exactly the same way:
![image](https://github.com/bcgov/orgbook-bc-client/assets/2395873/26dd5b66-9e89-4ccf-b9e5-2a5ca1c0964a)

**Comment by amanji** [comment]
OrgBook was redesigned by a UI/UX developer using BC Gov style recommendations at the time. I believe it was also approved by stakeholders. I think, given there has been such little activity in OrgBook development, we'd probably want to look at a deeper UI/UX refresh. I'm inclined to park this aside for now.
